[phases.setup]
nixPkgs = ["ffmpeg", "python311", "python311Packages.pip", "gcc", "pkg-config"]

[phases.install]
cmds = ["pip install --no-cache-dir -r requirements.txt"]

[phases.build]
cmds = []

[phases.start]
cmd = "gunicorn --bind 0.0.0.0:${PORT:-8080} main:app"
