
[phases.setup]
nixpkgs = ["ffmpeg", "python311", "gcc"]

[phases.install]
cmds = [
  "python3 -m pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[phases.start]
cmd = "python3 main.py"
