[build]
builder = "nixpacks"

[phases.setup]
nixpkgs = ["python311", "ffmpeg", "gcc"]

[phases.install]
cmds = [
  "pip install --no-cache-dir -r requirements.txt"
]

[start]
cmd = "gunicorn --bind 0.0.0.0:$PORT main:app"