[phases.setup]
nixPkgs = ["python311", "ffmpeg", "gcc"]

[phases.install]
cmds = ["python3 -m pip install --upgrade pip", "pip install -r requirements.txt"]

[phases.build]
cmds = []

[phases.start]
cmds = ["gunicorn --bind 0.0.0.0:$PORT main:app"]