[build]
nixpacksVersion = "1.38.0"

[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "ffmpeg", "gcc"]

[phases.install]
cmds = ["pip install --no-cache-dir -r requirements.txt"]

[phases.start]
cmds = ["gunicorn --bind 0.0.0.0:$PORT main:app"]